💩
DiscordBotList/dblapi.js pull request #2
Opened 2018-02-27 21:53 UTC by EXtremeExploit

ADDED: TypeScript for index.js
ADDED: Dependencies on README.md
ADDED: test/ to .gitignore

2018-02-27 21:59 UTC, tonkku107 requested changes

2018-02-27 21:59 UTC, tonkku107 commented on package.json
> +    "discord.js": "^11.3.0",
Remove discord.js from dependencies.
Not everyone using this module is using discord.js and installing discord.js just for this module is overkill

2018-02-27 21:59 UTC, tonkku107 commented on README.md
> +### Dependencies
The readme doesn't need a dependencies section.
npm handles those via package.json

2018-02-27 22:41 UTC, EXtremeExploit commented
Check PR now, i commited your requests

2018-02-27 23:10 UTC, tonkku107 requested changes

2018-02-27 23:10 UTC, tonkku107 commented on index.js
> +const { Client, Shard } = require('discord.js')
You're still requiring discord.js, this would cause errors

2018-02-27 23:10 UTC, tonkku107 commented on ts/index.d.ts
> +import { Client, Shard } from "discord.js";
Same here

2018-02-27 23:16 UTC, EXtremeExploit commented
Fixed

2018-02-27 23:16 UTC, tonkku107 commented
Would you be able to type client and shard in some other way?

2018-02-28 00:21 UTC, EXtremeExploit commented
Fixed x2

2018-02-28 12:56 UTC, tonkku107 commented
I don't see a new commit?

2018-02-28 13:38 UTC, EXtremeExploit commented
then if you want a proper typing, i can set that `any` to Client, but that's specific to a library

2018-02-28 16:19 UTC, tonkku107 commented
#3

2018-02-28 16:19 UTC, closed without merging